"use strict";
let places = ['Italy', 'Germany', 'Agra', 'Eifel Tower', 'Times Square'];
console.log('Orignal ' + places);
console.log('Copy ' + [...places].sort());
console.log('Orignal ' + places);
console.log('Orignal ' + places);
console.log('Orignal ' + places.reverse());
console.log('Orignal ' + places.reverse());
console.log('Orignal ' + places.sort());
console.log('Orignal ' + places.sort().reverse());
